language: scala

jdk: oraclejdk8

scala:
  - 2.11.8

sudo: false

before_install:
  - add-apt-repository -y ppa:marutter/c2d4u
  - apt-get update
  - apt-get install pandoc

script:
  - sbt test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  branch: md5deep
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/
    - $HOME/.coursier
